services:
  gateway:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
    volumes:
      - ./services/gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - load_balancer
      - frontend
      - static_server

  load_balancer:
    image: nginx:1.25-alpine
    volumes:
      - ./services/load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

  api1:
    build:
      context: ./services/api
    env_file:
      - ./services/api/.env
    depends_on:
      - mongo_db
      - message_broker

  api2:
    build:
      context: ./services/api
    env_file:
      - ./services/api/.env
    depends_on:
      - mongo_db
      - message_broker

  frontend:
    build:
      context: ./services/frontend

  static_server:
    image: nginx:1.25-alpine
    volumes:
      - ./data/screenshots:/usr/share/nginx/html:ro

  # database:
  #   image: postgres:15.3-alpine
  #   env_file:
  #     - ./services/db/.env
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./data/db/pg:/var/lib/postgresql/data

  mongo_db:
    image: mongo:6.0.6
    ports:
      - '27017:27017'
    volumes:
      - ./data/db/mongo:/data/db

  message_broker:
    image: rabbitmq:3.12-alpine
    env_file:
      - ./services/message-broker/.env
    volumes:
      - ./data/broker:/var/lib/rabbitmq/

  scrap_worker1:
    build:
      context: ./services/scrap-worker
    env_file:
      - ./services/scrap-worker/.env
    volumes:
      - ./data/screenshots:/app/screenshots
    depends_on:
      - mongo_db
      - message_broker

  scrap_worker2:
    build:
      context: ./services/scrap-worker
    env_file:
      - ./services/scrap-worker/.env
    volumes:
      - ./data/screenshots:/app/screenshots
    depends_on:
      - mongo_db
      - message_broker
